name: PR needs have changeset
on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    name: Validete changeset
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Validete that changeset is exists
        run: npx changeset status --since=develop
